services:
  blog:
    image: registry.noelvega.dev/blog:main
    container_name: app-blog
    networks:
      - infra
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.rule=Host(`blog.noelvega.dev`)"
      - "traefik.http.routers.blog.entrypoints=websecure"
      - "traefik.http.routers.blog.tls.certresolver=letsencrypt"
      - "traefik.http.services.blog.loadbalancer.server.port=80"
    restart: unless-stopped

  storage-api:
    image: registry.noelvega.dev/storage-api:main
    container_name: app-storage
    environment:
      - STORAGE_ROOT_PATH=/data/storage
    volumes:
      - /var/lib/storage:/data/storage
    networks:
      - infra
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.storage.rule=Host(`storage.noelvega.dev`)"
      - "traefik.http.routers.storage.entrypoints=websecure"
      - "traefik.http.routers.storage.tls.certresolver=letsencrypt"
      - "traefik.http.services.storage.loadbalancer.server.port=5000"
    restart: unless-stopped

networks:
  infra:
    external: true
